In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("data/chebi_submission_example.parquet", engine='fastparquet')

In [3]:
df

,mol_id,SMILES,class_0,class_1,class_2,class_3,class_4,class_5,class_6,class_7,...,class_490,class_491,class_492,class_493,class_494,class_495,class_496,class_497,class_498,class_499
0,mol_6861,OC[C@H]1O[C@H](O[C@H]2C(O)O[C@H](CO)[C@@H](O)[...,0,0,1,0,0,0,0,1,...,1,1,0,0,0,1,1,0,0,0
1,mol_29793,O.O=C([O-])CC(O)(CC(=O)[O-])C(=O)[O-].[K+].[K+...,1,1,1,0,0,0,0,1,...,0,1,0,1,1,0,0,0,0,1
2,mol_26953,CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C\CC/C(C)=C...,1,0,0,1,1,0,1,1,...,0,0,0,1,0,1,1,1,1,0
3,mol_26053,C=C1CCC(C(C)C)CC1,1,1,0,1,1,0,0,0,...,1,1,1,1,0,1,1,1,1,0
4,mol_18653,O=C(O)C1CCCCC1=O,0,0,0,0,1,0,0,1,...,0,1,0,1,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11218,mol_13480,Oc1cc2cc[nH]c2cc1O,0,0,0,1,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
11219,mol_42067,CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(C[C@]...,1,1,0,0,0,0,0,1,...,0,0,0,1,0,0,1,1,1,0
11220,mol_43978,N[C@@H](CCC(=O)[O-])C(O)=Nc1ccc2ccccc2c1,1,1,1,0,0,1,0,1,...,1,1,1,1,1,0,1,0,1,1
11221,mol_16268,COc1cc(-c2[o+]c3cc(O)cc(O)c3cc2O[C@@H]2O[C@H](...,0,1,1,0,0,1,0,0,...,0,1,1,0,1,0,1,0,0,1
11222,mol_36270,CCCCCCC=CCCCCCCCCC(=O)O,0,0,0,1,0,1,1,1,...,1,0,0,1,1,1,0,1,1,1

In [4]:
test_df = pd.read_parquet('data/chebi_dataset_test_empty.parquet', engine='fastparquet')

In [5]:
test_df

          mol_id                                             SMILES
0       mol_6861  OC[C@H]1O[C@H](O[C@H]2C(O)O[C@H](CO)[C@@H](O)[...
1      mol_29793  O.O=C([O-])CC(O)(CC(=O)[O-])C(=O)[O-].[K+].[K+...
2      mol_26953  CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C\CC/C(C)=C...
3      mol_26053                                  C=C1CCC(C(C)C)CC1
4      mol_18653                                   O=C(O)C1CCCCC1=O
...          ...                                                ...
11218  mol_13480                                 Oc1cc2cc[nH]c2cc1O
11219  mol_42067  CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(C[C@]...
11220  mol_43978           N[C@@H](CCC(=O)[O-])C(O)=Nc1ccc2ccccc2c1
11221  mol_16268  COc1cc(-c2[o+]c3cc(O)cc(O)c3cc2O[C@@H]2O[C@H](...
11222  mol_36270                            CCCCCCC=CCCCCCCCCC(=O)O

[11223 rows x 2 columns]